version: "3"
services:
  serve:
    container_name: solvents-frontEnd
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    expose:
      - 3000
    restart: always
    ports:
      - "3000:3000"